Display Ship Name in Window Titles
jalehman/port pull request #177
Opened 2022-03-18 17:21 UTC by latterbolden

closes https://github.com/urbit/port/issues/149

Adds support for optionally showing the name of the ship in spawned window titles. 

While working on this, I discovered large portions of the code for spawning new windows was not being executed due to (what I presume is) a bug, more details below.

## Design Decisions
- Main process uses Electron ipc to get the ship name from Renderer rather than asking Background for it directly
- After playing around with the styling a bit, I thought the `Groups (~latter-bolden)` formatting looked best in app
- For users who primarily use a single ship, this feature isn't really necessary and detracts from the visual experience (imo). As such, I made it an option that is off by default

## Same App Detection Bug
The `onNavigation` helper relied on a path check that didn't seem to be working correctly. When opening tiles from Grid, the path name it looked for to determine whether you're navigating to a new app was `/` which caused it to always register a match and duck out at the first conditional. This also meant spawned windows were not setting up subsequent navigation handlers in `main-window`.

After fixing the issue, new window functionality wasn't operating as expected (external links opened in browser, only able to open one window per app across all ships, etc.). I tried to interpret the intentions of the code and tweaked it accordingly. 

Compared to current Port functionality, the only major user facing difference is that opening apps repeatedly focuses on the existing window rather than spawning new ones. Opening the same app from another ship works as expected though.

2022-03-27 11:19 UTC, arthyn requested changes
This is awesome. Just a few small changes and then it's good to go.

2022-03-27 11:19 UTC, arthyn commented on src/renderer/ship/Launch.tsx
> +                shipName: getCometShortName(pier.shipName).trim()
We should add a backup of name if shipname is empty, like for remote ships.

2022-03-27 11:19 UTC, arthyn commented on src/main/helpers.ts
> +  if (!linkIsInternal(targetUrl, urlToGo) && blockExternal) {
We actually don't even use this `blockExternal` so it's safe to kill this leg of the if statement, and you can remove it as a param. It's holdover from some stuff I copied from nativefier.

2022-03-27 11:19 UTC, arthyn commented on src/main/helpers.ts
> +      .replace(`${targetUrl.protocol}//${targetUrl.hostname}${portPathSegment}`, '');
Instead of this, I believe you can just replace `targetUrl.hostname` with `targetUrl.host` and it will include the port

2022-03-27 11:19 UTC, arthyn commented on src/main/helpers.ts
> +  const sameApp = sameHost && targetUrl.pathname.split('/')[1] === url.pathname.split('/')[1];
I don't think this is what we want either, but I also think this variable can just be removed here and from the check below.

2022-03-30 00:34 UTC, latterbolden commented on src/renderer/ship/Launch.tsx
> +                shipName: getCometShortName(pier.shipName).trim()
Uses the input name as a fallback now

2022-03-30 16:57 UTC, merged